services:
  bambu-relay-h2d:
    image: bambu-relay
    container_name: bambu-relay-h2d
    environment:
        BAMBU_HOST: h2d
        ACCESS_CODE: 75875fca
        MQTT_HOST: mqtt.crpalmer.net
    restart: unless-stopped

  bambu-relay-x2d:
    image: bambu-relay
    container_name: bambu-relay-x2d
    environment:
        BAMBU_HOST: x2d
        ACCESS_CODE: f8764fa2
        MQTT_HOST: mqtt.crpalmer.net
    restart: unless-stopped
